### PR TITLE
Features: Using Bootstrap

### PR DESCRIPTION
**Pull request by ybadmus**
This project is submitted in fulfillment of the requirement for the "HTML and CSS" curriculum of the Microverse program.

### CODE REVIEW

**Review by Temmarie — CHANGES_REQUESTED** [review]
### Changes Required! :recycle:
Hi @ybadmus  ! 👋 👋 
### You have done well so far :clap: However, there are changes required for you to make for your project to be approved. Kindly work on them and submit them for another code review.

**General**

- [ ] Your project looks great. However, your project cannot be approved until you write a descriptive PR Message. It's essential that your repository is professional, as this is one of the things that potential colleagues will look at when recruiting team members. Please refer to [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) for more information.

- [ ] Also, your commits should be written in Imperative sentences. For example:
_**Wrong way: removed index.html file**_ 
 _**RIght way: Remove index.html file**_
Note that the First letter is capitalised.

- [ ] Fix your HTML validator errors. Use [this](https://validator.w3.org/) to check for errors.

- [ ] Fix all stylelint errors. 

**Recommended**

- [ ] Your page does not cover the full width of the screen like the Newsweek. Please fix this.

- **Navigation bar**
- [ ] Fix your navbar to look as similar as possible to the actual site's.

**Original**

Screenshot (104)

**Your clone**

Screenshot (105)

- [ ] It should change with RWD breakpoints.
**Original on medium screens**

Screenshot (107)

**Original on small screens**

Screenshot (106)

- **Main Content**

- [ ] Fix the Featured stories section to occupy a bit more width.

- [ ] The culture and travel section is missing the image tags. Please add it.

- [ ] Fix the debate section to look like that in the Newsweeek site.

**Original**

Screenshot (108)

**Your clone**

Screenshot (109)

- [ ] You are currently missing the Opinions header, that is, assuming what you have there is the Opinions column.

**Original**

Screenshot (111)

**Your clone**

Screenshot (110)

- [ ] For some reason, the section before " In the Magazine" looks different on your screen. Please fix it.

**Original clone**

Screenshot (112)

- [ ] On medium screens, your page does not change with the breakpoints at all. Please fix this.

**Original**

Screenshot (116)


**Your clone**

Screenshot (115)

- On small screens, it wraps to 1 column.

**Original**

Screenshot (118)

**Your clone**

Screenshot (117)](https://user-images.githubusercontent.com/49621279/100842198-c160d280-3478-11eb-9827-062d00c8cada.png)

- [ ] Your footer differs from that of the actual site's. Fix it, please.

**Original**

Screenshot (123)

**Your clone**

Screenshot (122)



__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by descholar-ceo** [comment]
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo)
## Please wait a bit ...

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @ybadmus  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your clone looks like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] The license link from your readme file doesn't exists
- [ ] The linkedin profile your provided in your readme file doesn't exist, fix that
- [ ] The login button and subscribe button in navbar should be aligned at the end of the navbar, currently they are far away from the rigtmost side of the navbar (in large screens)
- [ ] The search bar in small navbar shouldn't have any borders
- [ ] The debate section still need more work, the black `VS` circle should be centered both horizontally and vertically with the two horizontall lines
- [ ] The column below `The debate` section should have as a title `Opinion` not `the debate`
- [ ] Your clone doesn't have the `SUBSCRIBE` and `NEWSLETTER` section which comes before the footer, please work on it
- [ ] The newsweek logo in the footer should be an image not a simple h3 tag that you are using, please search for a red Newsweek logo and use it there.
- [ ] Make sure that the footer looks like the original
- [ ] This project doesn't have github actions for linters setup, please follow [this guideline and set them up](https://github.com/microverseinc/linters-config/tree/master/html-css)
# [Optional changes] :yellow_circle: 
:warning: Your commit messages should be in imperative mode or present tense, _i.e.:_ you should have written `Complet main feature changes` instead of writing `completed main feature changes`, refer [to this article for more details on how to write a good && professional commit message](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by descholar-ceo** [comment]
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @ybadmus  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your clone looks like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have implemented all the requested changes from the previous review, keep it up, and your project is really almost done.
:+1: It's okay this happens in real life as well, this project is big and one change lead to some more issues, but this is how things go even in real life, when you are working on big projects, but your project is on step away from the completion. Just implement the below required changes, then you will be ready to go.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] There are some titles that you are missing, learn the following screenshots to know more about them

| Your clone | Original page |
| --- | --- |
| Screenshot from 2020-12-04 00-32-58 | Screenshot from 2020-12-04 00-33-58|

:point_right: Could you see the difference :question: :question: :question: 
:point_right: As you can see, there titles which are missing on the left pictures, those titles are `U.S.`, `World`, `Business`, `Tech & Science`, `Culture`, `Sports`, Please re-consult the original page to see their respective positions and distribute them on your clone
_Note: You have 2 IN THE MAGAZINE titles, whereas in the original page there is one, remove unnecessary one_ 

- [ ] The subscribe section, it is made of two overlapping pictures, yours is just one picture. Please do it as the original is done

| Your clone | Original page |
| --- | --- |
| Screenshot from 2020-12-04 00-40-14|Screenshot from 2020-12-04 00-39-32|

:point_right: Make sure that `Newsletter section` and `Subscribe section` are not stretched on mobile screens

- [ ] The `Featured slideshow section` should occupy the whole screen width on mobile screen

| Your clone | Original page |
| --- | --- |
| Screenshot from 2020-12-04 00-41-51|Screenshot from 2020-12-04 00-43-12|

- [ ] The footer is distorted on mobile screen, and the logo in the footer is not being shown on mobile screens, fix that as well

| Your clone | Original page |
| --- | --- |
| Screenshot from 2020-12-04 00-45-32|Screenshot from 2020-12-04 00-44-42|
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Review by layzrd — CHANGES_REQUESTED** [review]
### Status: Require changes  ♲

Hi @ybadmus, I am [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR. Congratulations 🎊 👏, you did very well on this project. 👏👏👏  I appreciate your hard work in replicating newsweek.com.
 Most requirements have done 👌, Kindly fix the following issues.

[REQUIRED]

- [ ] My Turn section should have full width on small screens

- [ ] The Newsweek logo on the bottom should be on the left side

- [ ] The Editor pick page should have two articles per width

| Your Copy | Source |
| :---: | :---: |
|Screen Shot 2020-12-04 at 4 18 56 PM|Screen Shot 2020-12-04 at 4 18 43 PM|
|Screen Shot 2020-12-04 at 4 25 31 PM|Screen Shot 2020-12-04 at 4 25 40 PM|
|Screen Shot 2020-12-04 at 4 26 47 PM|Screen Shot 2020-12-04 at 4 26 17 PM|

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Review by jubaan — APPROVED** [review]
# :tada: :tada: :tada: :rotating_light: Status: Approved :rotating_light:  :tada: :tada: :tada:

#### :clap: :clap: Great job :hammer_and_pick:!! There are no more issues left to be addressed. 

# :tada: :tada: :tada: :rotating_light: Status: Approved :rotating_light:  :tada: :tada: :tada:

**Pull request merged**
